### ISSUE TITLE
Latte Dock is squared

### ISSUE THREAD

**Issue by Pireo** [vinceliuice/McMojave-kde#1]
I'm using manjaro kde and the latte dock with this theme (which is great and I thank you for this), doesn't have the smussed edges you see here: https://store.kde.org/p/1305006
I can't figure out why.

**Comment by vinceliuice** [comment]
Ｗhat I use is plank, not latte dock

**Comment by a-parhom** [comment]
> I'm using manjaro kde and the latte dock with this theme (which is great and I thank you for this), doesn't have the smussed edges you see here: https://store.kde.org/p/1305006
> I can't figure out why.

I've modified panel-background.svgz to have rounded corners in Latte Dock.
[panel-background.zip](https://github.com/vinceliuice/McMojave-kde/files/3911025/panel-background.zip)
