### ISSUE TITLE
 Thick frames

### ISSUE THREAD

**Issue by tetrois** [vinceliuice/McMojave-kde#17]
Thick frames when scaling 1.7 Plasma 5.17.5
![image](https://user-images.githubusercontent.com/10567840/73249011-154dbb80-41c5-11ea-9562-ea01e4655d8a.png)

**Comment by vinceliuice** [comment]
I'll upload a version for scaling 1.5

**Comment by gottabeleGIT** [comment]
I'm having the same issue, Plasma 5.18.1, scaling 1.7
