### ISSUE TITLE
McMojave-kde theme problem

### ISSUE THREAD

**Issue by vitabaks** [vinceliuice/McMojave-kde#19]
1. git clone https://github.com/vinceliuice/McMojave-kde.git

2. ./install.sh

result:
![image](https://user-images.githubusercontent.com/37010174/74033221-bd823200-49c6-11ea-816e-7a008391d6b8.png)

**Comment by vinceliuice** [comment]
Could you tell me your resolution and scaling setting?

**Comment by vitabaks** [comment]
![image](https://user-images.githubusercontent.com/37010174/74037480-659bf900-49cf-11ea-8307-9553a6802c91.png)

**Comment by vitabaks** [comment]
DPI: 96

**Comment by vinceliuice** [comment]
I see that your display resolution is 3840x2160, so did you set your resolution to 1920x1080 or the font scaling to 200%?

**Comment by vinceliuice** [comment]
I'll upload a aurorae theme 200% scaling version for 4k resolution, the default theme is made for 1080p resolution.

**Comment by vitabaks** [comment]
Thank you, I will wait for your correction.
So far I have a problem on all displays.

**Comment by vinceliuice** [comment]
You are welcome!

**Comment by sputniktr02** [comment]
@vinceliuice 
Hi, I don't think it's about resolution. I have 1080p Laptop and this is how it looks;
![Screenshot_20200207_211934](https://user-images.githubusercontent.com/31340272/74054993-2d58e280-49f0-11ea-901d-3c39730bbc2a.jpg)

Perhaps some Plasma issue?

**Comment by natrist** [comment]
I'm having the same issue on 1920x1200 resolution.

**Comment by vitabaks** [comment]
In the light version this problem is not observed:
![изображение](https://user-images.githubusercontent.com/37010174/74139893-2eaf2880-4c05-11ea-85f1-bd5e22eb7b6a.png)

**Comment by vinceliuice** [comment]
[McMojave.tar.gz](https://github.com/vinceliuice/McMojave-kde/files/4180592/McMojave.tar.gz)
-----------------------
@vitabaks @natrist Could you guys help me test this file I upload here, I use the light version make this dark theme. thanks!

**Comment by vinceliuice** [comment]
I don't know what went wrong because everything is working fine on my manjaro kde

**Comment by vitabaks** [comment]
@vinceliuice 
well, sort of good now 
![изображение](https://user-images.githubusercontent.com/37010174/74152093-99b92900-4c1e-11ea-9703-a819fab4efa2.png)

**Comment by vinceliuice** [comment]
OK! thanks @vitabaks , then I'll replace the dark version with this.

**Comment by vitabaks** [comment]
thanks @vinceliuice

**Comment by vinceliuice** [comment]
You are welcome!
