### ISSUE TITLE
the bar is at the bottom and not at the top

### ISSUE THREAD

**Issue by oxidodeazufre** [vinceliuice/McMojave-kde#22]

**Comment by vinceliuice** [comment]
You can unlock it and put it on top!

**Comment by vinceliuice** [comment]
Or you can add a new "McMojave panel" on right click menu at desktop, well first you should install the theme on github (layout-templates I only upload here),

**Comment by oxidodeazufre** [comment]
> You can unlock it and put it on top!

how?
