### ISSUE TITLE
大佬， aurorae McMojave-1.5x 有没有浅色light的呀？

### ISSUE THREAD

**Issue by zhaobingss** [vinceliuice/McMojave-kde#39]
大佬， aurorae McMojave-1.5x 有没有浅色light的呀？

**Comment by vinceliuice** [comment]
还没弄，我会更新一下，会有的

**Comment by zhaobingss** [comment]
> 还没弄，我会更新一下，会有的

好的，我暂时修改了下svg，坐等大佬更新

**Comment by apandada1** [comment]
It would be great to have a light colored McMojave-1.5x theme.

**Comment by apandada1** [comment]
Any updates? It would be great to have McMojave-1.25x and Mcmojave1.5x themes (light version), like the following
![image](https://user-images.githubusercontent.com/3063132/183825763-2360d660-d5df-4bab-b734-abab30064f2f.png)
