### ISSUE TITLE
McMojave-light - some items not visible with Dolphin.

### ISSUE THREAD

**Issue by Tuxman2** [vinceliuice/McMojave-kde#43]
Hello,

some items are not visible with Dolphin. See pictures:

![mojave-lightDolphin1](https://user-images.githubusercontent.com/23556606/139671943-6593501a-df27-4f08-bc0c-5a0ca968e4d3.jpg)

![mojave-lightDolphin2](https://user-images.githubusercontent.com/23556606/139671956-2dbacb3f-8e72-43e4-be79-7c0de910c569.jpg)

Can you have a look ?

Thanks.

**Comment by vinceliuice** [comment]
Change your icon theme

**Comment by Tuxman2** [comment]
Ok. I will test with another icon pack.

Regards.

**Comment by Tuxman2** [comment]
I changed the icon pack. It is solved now.

Thanks.
