### ISSUE TITLE
Please update to Plasma 6

### ISSUE THREAD

**Issue by Rtizer-9** [vinceliuice/McMojave-kde#49]
As you already know Plasma 6 has changed the way icons are implemented since you've already made the changes in whitesur theme, this theme also needs to be updated to Plasma 6. I like this one's icons much more but it's not working at the moment unlike Plasma 5.

Thanks

**Comment by vinceliuice** [comment]
Now it's fixed

**Comment by Rtizer-9** [comment]
Thanks for the quick response.

I redownloaded it from github thinking it'll work but it didn't and then I tried from plasma style > get new, but it still didn't work giving same outdated json error and I thought the kde store must be taking time to reflect the updated changes but it's already updated and then...

I looked at zip and several files still contain plasma version= 5.0. I tried to manually make changes but still no success.

Can you please take a look?

Earlier in plasma 5 I could have one theme for system and mcmojave icons for kde panel but now I can't.

**Comment by vinceliuice** [comment]
In plasma 6.0 panel and menu icons will use the one in icon themes, not use buildin icons in plama theme any more

**Comment by Rtizer-9** [comment]
Oops. Ok
