### ISSUE TITLE
No tree branch indicators in the light variation 

### ISSUE THREAD

**Issue by y-usuzumi** [vinceliuice/McMojave-kde#5]
Hi. The tree branches miss indicators in the light version. Compare:

![image](https://user-images.githubusercontent.com/1560189/62759137-1114d100-bab3-11e9-8074-3c0bfec7b0e0.png)

with:

![image](https://user-images.githubusercontent.com/1560189/62759170-2689fb00-bab3-11e9-8a01-bd5626f65f99.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by codedracula4ec** [comment]
Go to your **McMojave-light.kvconfig** in `~/.config/Kvantum/McMojave-light/` and:

1. Search for **[TreeExpander]**
2. Set **indicator.element** to tree
3. Save the file

![image](https://user-images.githubusercontent.com/62944284/78032035-c2b28c00-733a-11ea-81f3-7027db0a8916.png)

![image](https://user-images.githubusercontent.com/62944284/78032084-d827b600-733a-11ea-82f6-f471d263d327.png)

**Comment by y-usuzumi** [comment]
@codedracula4ec Yes that was exactly what I did.
I also compared the svg and the config files of the two variations and noticed more differences. Not sure it was on purpose or they diversed due to independent updates.

**Comment by vinceliuice** [comment]
Thanks!
